### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Dhruv-Pattel**
### Description

Created Code Of Conduct 

### Related Issues

N/A

### Screenshots

N/A

### Checklist

- [ ] I have tested these changes locally.
- [x] My code follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have added tests to cover my changes.

### Additional Notes

solved issue #39

### CODE REVIEW

**Comment by chandel-aman** [comment]
> solved issue #39

@Dhruv-Pattel There is a template provided for PR. Follow the template and update the description.

**Review by chandel-aman — APPROVED** [review]

**Comment by Dhruv-Pattel** [comment]
> > solved issue #39
> 
> @Dhruv-Pattel There is a template provided for PR. Follow the template and update the description.

I've made the required changes in the description. check that out

**Comment by chandel-aman** [comment]
@Dhruv-Pattel, you need to make a pull request to the `develop` branch. Raising a pull request against `main` will not be merged.

**Comment by Dhruv-Pattel** [comment]
I've changed the branch. Do you think it's fine now?

**Comment by Dhruv-Pattel** [comment]
hey @chandel-aman ! can you please assign me for my PR? 

(PR guidelines for gssoc leaderboard )
334841021-fcb036b9-ec8e-409e-a880-4abd43ac5c1b

**Comment by Dhruv-Pattel** [comment]
hey @chandel-aman ! I just come to know that "Level 1" label is not valid for getting points. 
Can you change it to "level1" (without space and all characters in lowercase)

**Comment by Dhruv-Pattel** [comment]
hey @chandel-aman ! can you change the label as I mentioned above?

**Pull request merged**
