### PR TITLE
Update Navbar.tsx

### PR DESCRIPTION
**Pull request by Rakshit-gen**
## Pull Request
Issue #16 

### Description

Added the link to github svg

### Checklist

- [x] I have tested these changes locally.
- [x] My code follows the project's coding guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by AkashSharma001** [comment]
@Rakshit-gen 
While running the checks, the lint and authorization checks failed. We only review when all checks are passed.

**Comment by Rakshit-gen** [comment]
Any ideas @AkashSharma001 on how to make them pass. I didn't do anything that could affect the main parts of the code just added an <a> tag in the header file.

Why are the issues occurring any idea??

**Comment by AkashSharma001** [comment]
@Rakshit-gen 
You need to adjust the indentation. 

Before fixing the indentation, do these steps:

1. Take the latest pull from upstream/develop
```
git pull upstream develop 
```
2. Install the dependencies
```
npm install
```
3. Run the lint check
```
npm run lint
```
4. Fix the errors

5. Stage your changes
```
git add .
```
6. Commit your changes 
```
git commit -m "commit message"
```

Once you commit the lint check will run again automatically, and you would only be allowed to commit once all the errors are fixed.

**Comment by Rakshit-gen** [comment]
Okay on it @AkashSharma001

**Comment by Rakshit-gen** [comment]
Try it now @AkashSharma001

**Comment by chandel-aman** [comment]
@Rakshit-gen It is not working.
Check this link https://deploy-preview-69--dev-tailoredui.netlify.app/
Also where there is change in package.lock.json?

**Pull request closed without merging**
