### PR TITLE
solves issue  #24

### PR DESCRIPTION
**Pull request by AMISH-KHAN**
## Pull Request

This PR closes the issue #24 

### Description

I have linked the logo to the home page

### CODE REVIEW

**Comment by AkashSharma001** [comment]
@AMISH-KHAN 
While running the checks, the lint and authorization checks failed. We only review when all checks are passed.

**Comment by AMISH-KHAN** [comment]
How can I solve this?

**Comment by chandel-aman** [comment]
> How can I solve this?
> 

1. Take the latest pull from upstream/develop
```
git pull upstream develop 
```
2. Install the dependencies
```
npm install
```
3. Run the lint check
```
npm run lint
```
4. Fix the errors
5. Stage your changes
```
git add .
```
6. Commit your changes 
```
git commit -m "commit message"
```

Once you commit the lint check will run again automatically, and you would only be allowed to commit once all the errors are fixed.

**Comment by AMISH-KHAN** [comment]
i think I have passed all the checks. @AkashSharma001 please review it.

**Comment by AkashSharma001** [comment]
@AkashSharma001 
Remove the contributor.md file from the pull request.

**Comment by AkashSharma001** [comment]
@AMISH-KHAN 
Remove the contributor.md file from the pull request.

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN Remove the contributor.md file from the pull request.

are you suggesting to delete the file CONTRIBUTING.md or undo the changes?

**Comment by chandel-aman** [comment]
> > @AMISH-KHAN Remove the contributor.md file from the pull request.
> 
> are you suggesting to delete the file CONTRIBUTING.md or undo the changes?
> 

Removing the CONTRIBUTING.md file changes from your pull request is being suggested.

I think you have not taken the latest pull from upstream/develop.

**Comment by AMISH-KHAN** [comment]
hey @chandel-aman  please review it. 
also when ever i commit I get this in my terminal which modifies the contributing.md file
Screenshot 2024-05-13 014522

**Review by chandel-aman — APPROVED** [review]

**Comment by AMISH-KHAN** [comment]
@chandel-aman please add gssoc lable

**Pull request merged**
