### PR TITLE
Added Links to buttons on home page

### PR DESCRIPTION
**Pull request by SaranshBangar**
### Description

1. Added links to hero section buttons
2. Added a new router link for components page

### Checklist

- [X] I have tested these changes locally.
- [X] My code follows the project's coding guidelines.
- [X] I have updated the documentation, if necessary.
- [X] I have added tests to cover my changes.

### Additional Notes

Resolves issue #19

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #19

**Comment by chandel-aman** [comment]
@SaranshBangar 
The design breaks


Design should be the same as earlier.

**Comment by SaranshBangar** [comment]
Done sir, I was not sure how adding the `<Link>` tag can change the CSS of the button but now I have resolved the issue

**Comment by AkashSharma001** [comment]
@SaranshBangar 
While running the checks, the lint and authorization checks failed. We only review when all checks are passed.

**Comment by SaranshBangar** [comment]
> @SaranshBangar While running the checks, the lint and authorization checks failed. We only review when all checks are passed.

Sir, the Lint issue can be resolved easily after switching from ReactJS to Next.js as in Next.js we just have to modify the `lint` script in `package.json` like this
```
"scripts": {
  "lint": "next lint --fix",
},
```

Then simply running `npm run lint` will fix all the classnames without an problem. 
As of now, this error would not hamper the performance of the website in any way

**Comment by chandel-aman** [comment]
> > @SaranshBangar While running the checks, the lint and authorization checks failed. We only review when all checks are passed.
> 
> Sir, the Lint issue can be resolved easily after switching from ReactJS to Next.js as in Next.js we just have to modify the `lint` script in `package.json` like this
> 
> ```
> "scripts": {
>   "lint": "next lint --fix",
> },
> ```
> 
> Then simply running `npm run lint` will fix all the classnames without an problem. As of now, this error would not hamper the performance of the website in any way

1. Firstly, we have not migrated to Next.js, so you need not concern yourself with what could be done when we do migrate.
2. Also, we understand that the order of class names won't affect the performance of the website, but it is done to maintain good coding practices.

So, please ensure that the check passes before we can merge your PR.

**Comment by SaranshBangar** [comment]
Sir, the documentation of Prettier and Tailwind both give different order for classnames to maintain consistency, even when I follow the later's documentation Prettier enforces its own order.

Moreover the linting error is not just coming from my PRs as I have added just a Link tag wrapping the buttons, the error comes from the framer motion divs that were already present (and deployed)

**Comment by chandel-aman** [comment]
As suggested earlier you need to resolve the errors for the check to pass.

Ask for help if you are facing any difficulty.

**Comment by chandel-aman** [comment]
Closing due to no activity.

**Comment by SaranshBangar** [comment]
> Closing due to no activity.

Sir, I have already raised a PR

**Comment by chandel-aman** [comment]
> > Closing due to no activity.
> 
> Sir, I have already raised a PR

Checks were failing and there was no update.

**Comment by chandel-aman** [comment]
Raise a new PR if you have resolved this.

**Pull request closed without merging**
